-- =============================================================================
-- V1: esquema inicial de Citero.
-- SQL portable para PostgreSQL (producción) y H2 (desarrollo).
-- =============================================================================

CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(100) NOT NULL,
    password       VARCHAR(255) NOT NULL,
    phone          VARCHAR(20),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE businesses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        BIGINT NOT NULL,
    name            VARCHAR(100) NOT NULL,
    slug            VARCHAR(100) NOT NULL,
    description     TEXT,
    created_at      TIMESTAMP NOT NULL,
    logo_url        VARCHAR(500),
    address         VARCHAR(255),
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    phone           VARCHAR(30),
    cover_image_url VARCHAR(500),
    instagram_url   VARCHAR(255),
    facebook_url    VARCHAR(255),
    tiktok_url      VARCHAR(255),
    twitter_url     VARCHAR(255),
    whatsapp_number VARCHAR(30),
    timezone        VARCHAR(60),
    CONSTRAINT uk_businesses_slug UNIQUE (slug),
    CONSTRAINT fk_businesses_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE business_configs (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id                  BIGINT NOT NULL,
    reservation_mode             VARCHAR(20) NOT NULL,
    cancellation_tolerance_hours INTEGER NOT NULL,
    enable_penalties             BOOLEAN NOT NULL,
    max_strikes                  INTEGER NOT NULL,
    default_opening_time         TIME NOT NULL,
    default_closing_time         TIME NOT NULL,
    enable_reminders             BOOLEAN NOT NULL,
    reminder_24h_enabled         BOOLEAN NOT NULL,
    reminder_2h_enabled          BOOLEAN NOT NULL,
    CONSTRAINT uk_business_configs_business UNIQUE (business_id),
    CONSTRAINT fk_business_configs_business FOREIGN KEY (business_id) REFERENCES businesses (id)
);

CREATE TABLE business_schedules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,
    open_time   TIME NOT NULL,
    close_time  TIME NOT NULL,
    is_closed   BOOLEAN NOT NULL,
    CONSTRAINT uk_business_schedule_day UNIQUE (business_id, day_of_week),
    CONSTRAINT fk_business_schedules_business FOREIGN KEY (business_id) REFERENCES businesses (id)
);

CREATE TABLE services (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id      BIGINT NOT NULL,
    name             VARCHAR(100) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    price            NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_services_business FOREIGN KEY (business_id) REFERENCES businesses (id)
);

CREATE TABLE staff (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT NOT NULL,
    user_id       BIGINT,
    contact_email VARCHAR(100),
    custom_name   VARCHAR(100),
    CONSTRAINT fk_staff_business FOREIGN KEY (business_id) REFERENCES businesses (id),
    CONSTRAINT fk_staff_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE staff_services (
    staff_id   BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    CONSTRAINT pk_staff_services PRIMARY KEY (staff_id, service_id),
    CONSTRAINT fk_staff_services_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT fk_staff_services_service FOREIGN KEY (service_id) REFERENCES services (id)
);

CREATE TABLE appointments (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id            BIGINT NOT NULL,
    staff_id             BIGINT NOT NULL,
    service_id           BIGINT NOT NULL,
    start_time           TIMESTAMP NOT NULL,
    end_time             TIMESTAMP NOT NULL,
    status               VARCHAR(20) NOT NULL,
    created_at           TIMESTAMP NOT NULL,
    reminder_24h_sent_at TIMESTAMP,
    reminder_2h_sent_at  TIMESTAMP,
    CONSTRAINT fk_appointments_client FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_appointments_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT fk_appointments_service FOREIGN KEY (service_id) REFERENCES services (id)
);

CREATE INDEX idx_appointments_staff_start ON appointments (staff_id, start_time);
CREATE INDEX idx_appointments_status_start ON appointments (status, start_time);
CREATE INDEX idx_appointments_client ON appointments (client_id);

CREATE TABLE client_reputations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    BIGINT NOT NULL,
    business_id  BIGINT NOT NULL,
    strike_count INTEGER NOT NULL,
    is_blocked   BOOLEAN NOT NULL,
    last_updated TIMESTAMP NOT NULL,
    CONSTRAINT uk_client_reputations_client_business UNIQUE (client_id, business_id),
    CONSTRAINT fk_client_reputations_client FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_client_reputations_business FOREIGN KEY (business_id) REFERENCES businesses (id)
);

CREATE TABLE refresh_tokens (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    token_hash       VARCHAR(64) NOT NULL,
    session_id       VARCHAR(36) NOT NULL,
    expires_at       TIMESTAMP NOT NULL,
    created_at       TIMESTAMP NOT NULL,
    revoked          BOOLEAN NOT NULL,
    replaced_by_hash VARCHAR(64),
    user_agent       VARCHAR(255),
    ip_address       VARCHAR(45),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE UNIQUE INDEX idx_refresh_token_hash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_token_session ON refresh_tokens (session_id);

CREATE TABLE otp_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target          VARCHAR(100) NOT NULL,
    code            VARCHAR(10) NOT NULL,
    expiration_time TIMESTAMP NOT NULL,
    is_used         BOOLEAN NOT NULL,
    attempts        INTEGER NOT NULL,
    purpose         VARCHAR(30) NOT NULL,
    created_at      TIMESTAMP NOT NULL
);
