-- =============================================================================
-- V1: esquema inicial consolidado de Citero.
-- SQL portable para PostgreSQL (producción) y H2 (desarrollo).
--
-- Consolida las antiguas migraciones V1..V13 en un único script, ya que el
-- proyecto parte de una base de datos nueva. Refleja sólo el estado final del
-- esquema (se omitieron tablas/columnas creadas y luego eliminadas).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Usuarios
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(100) NOT NULL,
    password            VARCHAR(255) NOT NULL,
    phone               VARCHAR(20),
    name                VARCHAR(100),
    email_verified      BOOLEAN NOT NULL DEFAULT FALSE,
    -- Cuenta creada automáticamente al reservar como invitado (email reclamable al registrarse).
    is_guest            BOOLEAN NOT NULL DEFAULT FALSE,
    -- Segundo factor (TOTP) opcional.
    totp_secret         VARCHAR(64),
    totp_enabled        BOOLEAN NOT NULL DEFAULT FALSE,
    totp_recovery_codes TEXT,
    created_at          TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- -----------------------------------------------------------------------------
-- Negocios
-- -----------------------------------------------------------------------------
CREATE TABLE businesses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        BIGINT NOT NULL,
    name            VARCHAR(100) NOT NULL,
    slug            VARCHAR(100) NOT NULL,
    description     TEXT,
    created_at      TIMESTAMP NOT NULL,
    logo_url        VARCHAR(500),
    address         VARCHAR(255),
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    phone           VARCHAR(30),
    cover_image_url VARCHAR(500),
    instagram_url   VARCHAR(255),
    facebook_url    VARCHAR(255),
    tiktok_url      VARCHAR(255),
    twitter_url     VARCHAR(255),
    whatsapp_number VARCHAR(30),
    timezone        VARCHAR(60),
    CONSTRAINT uk_businesses_slug UNIQUE (slug),
    CONSTRAINT fk_businesses_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE business_configs (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id                BIGINT NOT NULL,
    reservation_mode           VARCHAR(20) NOT NULL,
    -- Informativo: horas antes del inicio por debajo de las cuales una cancelación
    -- del cliente se marca como "tardía". No aplica sanciones.
    cancellation_tolerance_hours INTEGER NOT NULL,
    -- Si true, el staff (no dueño) ve la agenda completa; si false, sólo la propia.
    staff_can_view_full_agenda BOOLEAN NOT NULL DEFAULT FALSE,
    default_opening_time       TIME NOT NULL,
    default_closing_time       TIME NOT NULL,
    enable_reminders           BOOLEAN NOT NULL,
    reminder_24h_enabled       BOOLEAN NOT NULL,
    reminder_2h_enabled        BOOLEAN NOT NULL,
    CONSTRAINT uk_business_configs_business UNIQUE (business_id),
    CONSTRAINT fk_business_configs_business FOREIGN KEY (business_id) REFERENCES businesses (id)
);

-- -----------------------------------------------------------------------------
-- Horarios: reglas semanales o excepciones por fecha, cada una con franjas.
-- -----------------------------------------------------------------------------
CREATE TABLE business_schedule_days (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT NOT NULL,
    day_of_week   VARCHAR(10),
    specific_date DATE,
    is_closed     BOOLEAN NOT NULL,
    CONSTRAINT uk_schedule_day_weekday UNIQUE (business_id, day_of_week),
    CONSTRAINT uk_schedule_day_date UNIQUE (business_id, specific_date),
    CONSTRAINT ck_schedule_day_scope CHECK (
        (day_of_week IS NOT NULL AND specific_date IS NULL) OR
        (day_of_week IS NULL AND specific_date IS NOT NULL)
    ),
    CONSTRAINT fk_schedule_days_business FOREIGN KEY (business_id) REFERENCES businesses (id) ON DELETE CASCADE
);

CREATE TABLE business_schedule_periods (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_day_id BIGINT NOT NULL,
    open_time       TIME NOT NULL,
    close_time      TIME NOT NULL,
    CONSTRAINT ck_schedule_period_range CHECK (open_time < close_time),
    CONSTRAINT fk_schedule_periods_day FOREIGN KEY (schedule_day_id) REFERENCES business_schedule_days (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Servicios y profesionales
-- -----------------------------------------------------------------------------
CREATE TABLE services (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id      BIGINT NOT NULL,
    name             VARCHAR(100) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    price            NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_services_business FOREIGN KEY (business_id) REFERENCES businesses (id)
);

CREATE TABLE staff (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT NOT NULL,
    user_id       BIGINT,
    contact_email VARCHAR(100),
    custom_name   VARCHAR(100),
    CONSTRAINT fk_staff_business FOREIGN KEY (business_id) REFERENCES businesses (id),
    CONSTRAINT fk_staff_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE staff_services (
    staff_id   BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    CONSTRAINT pk_staff_services PRIMARY KEY (staff_id, service_id),
    CONSTRAINT fk_staff_services_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT fk_staff_services_service FOREIGN KEY (service_id) REFERENCES services (id)
);

-- -----------------------------------------------------------------------------
-- Turnos
-- -----------------------------------------------------------------------------
CREATE TABLE appointments (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id            BIGINT NOT NULL,
    staff_id             BIGINT NOT NULL,
    service_id           BIGINT NOT NULL,
    start_time           TIMESTAMP NOT NULL,
    end_time             TIMESTAMP NOT NULL,
    status               VARCHAR(20) NOT NULL,
    created_at           TIMESTAMP NOT NULL,
    reminder_24h_sent_at TIMESTAMP,
    reminder_2h_sent_at  TIMESTAMP,
    -- Informativo: la cancelación (del cliente) se hizo dentro de la tolerancia.
    cancelled_late       BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_appointments_client FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_appointments_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT fk_appointments_service FOREIGN KEY (service_id) REFERENCES services (id)
);

CREATE INDEX idx_appointments_staff_start ON appointments (staff_id, start_time);
CREATE INDEX idx_appointments_status_start ON appointments (status, start_time);
CREATE INDEX idx_appointments_client ON appointments (client_id);

-- -----------------------------------------------------------------------------
-- Clientes del negocio (bloqueo manual; sin sanciones automáticas)
-- -----------------------------------------------------------------------------
CREATE TABLE business_clients (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    BIGINT NOT NULL,
    business_id  BIGINT NOT NULL,
    is_blocked   BOOLEAN NOT NULL,
    block_reason VARCHAR(255),
    last_updated TIMESTAMP NOT NULL,
    CONSTRAINT uk_business_clients_client_business UNIQUE (client_id, business_id),
    CONSTRAINT fk_business_clients_client FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_business_clients_business FOREIGN KEY (business_id) REFERENCES businesses (id)
);

-- -----------------------------------------------------------------------------
-- Sesiones (refresh tokens) y OTP
-- -----------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,
    session_id  VARCHAR(36) NOT NULL,
    expires_at  TIMESTAMP NOT NULL,
    created_at  TIMESTAMP NOT NULL,
    revoked     BOOLEAN NOT NULL,
    user_agent  VARCHAR(255),
    ip_address  VARCHAR(45),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE UNIQUE INDEX idx_refresh_token_hash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_token_session ON refresh_tokens (session_id);

CREATE TABLE otp_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target          VARCHAR(100) NOT NULL,
    -- Hash HMAC-SHA256 (hex de 64 chars) del código, no texto plano.
    code            VARCHAR(64) NOT NULL,
    expiration_time TIMESTAMP NOT NULL,
    is_used         BOOLEAN NOT NULL,
    attempts        INTEGER NOT NULL,
    purpose         VARCHAR(30) NOT NULL,
    created_at      TIMESTAMP NOT NULL
);
