-- V5: horarios con múltiples franjas por día y excepciones por fecha.
-- business_schedule_days: un "día" que es una regla semanal (day_of_week) o una
--   excepción puntual (specific_date). Cada día tiene una o más franjas.
-- business_schedule_periods: las franjas horarias (apertura/cierre) de cada día.

CREATE TABLE business_schedule_days (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT NOT NULL,
    day_of_week   VARCHAR(10),
    specific_date DATE,
    is_closed     BOOLEAN NOT NULL,
    CONSTRAINT uk_schedule_day_weekday UNIQUE (business_id, day_of_week),
    CONSTRAINT uk_schedule_day_date UNIQUE (business_id, specific_date),
    CONSTRAINT ck_schedule_day_scope CHECK (
        (day_of_week IS NOT NULL AND specific_date IS NULL) OR
        (day_of_week IS NULL AND specific_date IS NOT NULL)
    ),
    CONSTRAINT fk_schedule_days_business FOREIGN KEY (business_id) REFERENCES businesses (id) ON DELETE CASCADE
);

CREATE TABLE business_schedule_periods (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_day_id BIGINT NOT NULL,
    open_time       TIME NOT NULL,
    close_time      TIME NOT NULL,
    CONSTRAINT ck_schedule_period_range CHECK (open_time < close_time),
    CONSTRAINT fk_schedule_periods_day FOREIGN KEY (schedule_day_id) REFERENCES business_schedule_days (id) ON DELETE CASCADE
);

DROP TABLE business_schedules;
